version: '3'

services:
  db:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_PASSWORD: dolphins
      POSTGRES_USER: sample
      POSTGRES_DB: sample
    container_name: sample-db
    ports:
      - '5432:5432'
