/*
 * This file is generated by jOOQ.
 */
package com.github.yaseenkadir.jipba.tables.pojos;


import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Foobar {

    private final Long   id;
    private final byte[] data;

    public Foobar(Foobar value) {
        this.id = value.id;
        this.data = value.data;
    }

    public Foobar(
        Long   id,
        byte[] data
    ) {
        this.id = id;
        this.data = data;
    }

    public Long getId() {
        return this.id;
    }

    public byte[] getData() {
        return this.data;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Foobar other = (Foobar) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (data == null) {
            if (other.data != null)
                return false;
        }
        else if (!Arrays.equals(data, other.data))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.data == null) ? 0 : Arrays.hashCode(this.data));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Foobar (");

        sb.append(id);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
